### ISSUE TITLE
Create week overview page (5)

### ISSUE THREAD

**Issue by jhviggo** [jhviggo/capex-SG#6]
When you click on a week you will be shown information about that week. The page should show some information such as week status/color, list of developers assigned to the project and their names, statuses, and what projects each is assigned to (example, a developer can be assigned to multiple projects).

![image](https://user-images.githubusercontent.com/8568547/79971057-1de82200-8494-11ea-99ed-2cf5543a4345.png)

**Comment by KasperLeiszner** [comment]
I still need to implement the route to the pug file. Also i need to style my dropdowns with js code and css.
